// SPDX-License-Identifier: MIT
export default function doesItemHaveDurability(itemName: string) {
	return [
		"Assault Rifle",
		"Bow",
		"Chainsaw",
		"Chitin Boots",
		"Chitin Chestpiece",
		"Chitin Gauntlets",
		"Chitin Helmet",
		"Chitin Leggings",
		"Cloth Boots",
		"Cloth Gloves",
		"Cloth Hat",
		"Cloth Pants",
		"Cloth Shirt",
		"Desert Cloth Boots",
		"Desert Cloth Gloves",
		"Desert Cloth Pants",
		"Desert Cloth Shirt",
		"Desert Goggles and Hat",
		"Compound Bow",
		"Crossbow",
		"Fabricated Pistol",
		"Fabricated Sniper Rifle",
		"Flak Boots",
		"Flak Chestpiece",
		"Flak Gauntlets",
		"Flak Helmet",
		"Flak Leggings",
		"Fur Boots",
		"Fur Cap",
		"Fur Chestpiece",
		"Fur Gauntlets",
		"Fur Leggings",
		"Ghillie Boots",
		"Ghillie Chestpiece",
		"Ghillie Gauntlets",
		"Ghillie Leggings",
		"Ghillie Mask",
		"Hazard Suit Boots",
		"Hazard Suit Gloves",
		"Hazard Suit Hat",
		"Hazard Suit Pants",
		"Hazard Suit Shirt",
		"Heavy Miner's Helmet",
		"Hide Boots",
		"Hide Gloves",
		"Hide Hat",
		"Hide Pants",
		"Hide Shirt",
		"Lance",
		"Longneck Rifle",
		"Metal Hatchet",
		"Metal Pick",
		"Metal Shield",
		"Metal Sickle",
		"Night Vision Goggles",
		"Pike",
		"Pump-Action Shotgun",
		"Riot Boots",
		"Riot Chestpiece",
		"Riot Gauntlets",
		"Riot Helmet",
		"Riot Leggings",
		"Riot Shield",
		"Roll Rat Saddle",
		"SCUBA Flippers",
		"SCUBA Leggings",
		"SCUBA Mask",
		"SCUBA Tank",
		"Shotgun",
		"Simple Pistol",
		"Slingshot",
		"Spear",
		"Stone Hatchet",
		"Stone Pick",
		"Sword",
		"Torch",
		"Whip",
		"Wooden Club",
		"Wooden Shield"
	].indexOf(itemName) >= 0;
}